"""Seed / sample listings shaped like scrubbed bengaluru.rent pins.

Used when live fetch is unavailable. All rows are currently available,
include source_url + lat/lon, and contain zero PII fields.
"""

from __future__ import annotations

SEED_RAW_LISTINGS: list[dict] = [
    {
        "id": "km-201",
        "source_url": "https://bengaluru.rent/#listing-km-201",
        "location": "Bengaluru",
        "locality": "Koramangala",
        "rent": 32000,
        "bedrooms": 2,
        "furnishing": "semi-furnished",
        "amenities": ["parking", "balcony", "security"],
        "society_name": "Sony Signal Residency",
        "square_footage": 1050,
        "available_from": "2026-08-25",
        "deposit_amount": 64000,
        "listing_type": "whole flat",
        "food_preference": "veg",
        "smoking_preference": "no smoking",
        "availability_status": "available",
        "latitude": 12.9352,
        "longitude": 77.6245,
        # intentionally dirty — must be scrubbed before upsert
        "owner_name": "SHOULD_BE_REMOVED",
        "phone": "9876543210",
        "email": "leak@example.com",
    },
    {
        "id": "km-202",
        "source_url": "https://bengaluru.rent/#listing-km-202",
        "location": "Bengaluru",
        "locality": "Koramangala",
        "rent": 28000,
        "bedrooms": 2,
        "furnishing": "furnished",
        "amenities": ["parking", "power-backup"],
        "society_name": "5th Block Nest",
        "square_footage": 980,
        "available_from": "2026-09-01",
        "deposit_amount": 84000,
        "listing_type": "whole flat",
        "food_preference": "non-veg",
        "smoking_preference": "any",
        "availability_status": "available",
        "latitude": 12.9345,
        "longitude": 77.6210,
    },
    {
        "id": "km-203",
        "source_url": "https://bengaluru.rent/#listing-km-203",
        "location": "Bengaluru",
        "locality": "Koramangala",
        "rent": 45000,
        "bedrooms": 2,
        "furnishing": "furnished",
        "amenities": ["parking", "balcony", "gym", "pet-friendly"],
        "society_name": "Forum View Apartments",
        "square_footage": 1250,
        "available_from": "2026-08-21",
        "deposit_amount": 90000,
        "listing_type": "whole flat",
        "food_preference": "any",
        "smoking_preference": "smoking allowed",
        "availability_status": "available",
        "latitude": 12.9368,
        "longitude": 77.6112,
    },
    {
        "id": "km-204",
        "source_url": "https://bengaluru.rent/#listing-km-204",
        "location": "Bengaluru",
        "locality": "Koramangala",
        "rent": 34000,
        "bedrooms": 2,
        "furnishing": "unfurnished",
        "amenities": ["balcony"],  # no parking — hard-filter test
        "society_name": "Jyoti Nivas Lane",
        "square_footage": 900,
        "available_from": "2026-09-15",
        "deposit_amount": 102000,
        "listing_type": "room in a flat",
        "food_preference": "veg",
        "smoking_preference": "no smoking",
        "gender": "female",
        "availability_status": "available",
        "latitude": 12.9310,
        "longitude": 77.6228,
    },
    {
        "id": "km-205",
        "source_url": "https://bengaluru.rent/#listing-km-205",
        "location": "Bengaluru",
        "locality": "Koramangala",
        "rent": 30000,
        "bedrooms": 3,
        "furnishing": "semi-furnished",
        "amenities": ["parking", "pet-friendly"],
        "society_name": "80 Feet Road Homes",
        "square_footage": 1400,
        "available_from": "2026-10-01",
        "deposit_amount": 60000,
        "listing_type": "whole flat",
        "food_preference": "any",
        "smoking_preference": "any",
        "availability_status": "available",
        "latitude": 12.9381,
        "longitude": 77.6280,
    },
    {
        "id": "km-206",
        "source_url": "https://bengaluru.rent/#listing-km-206",
        "location": "Bengaluru",
        "locality": "Koramangala",
        "rent": 31000,
        "bedrooms": 2,
        "furnishing": "semi-furnished",
        "amenities": ["parking", "balcony", "elevator"],
        "society_name": "St John's Road Court",
        "square_footage": 1020,
        "available_from": "2026-08-28",
        "deposit_amount": 93000,
        "listing_type": "whole flat",
        "food_preference": "non-veg",
        "smoking_preference": "no smoking",
        "availability_status": "available",
        "latitude": 12.9338,
        "longitude": 77.6195,
    },
    {
        "id": "km-207",
        "source_url": "https://bengaluru.rent/#listing-km-207",
        "location": "Bengaluru",
        "locality": "Koramangala",
        "rent": 29500,
        "bedrooms": 2,
        "furnishing": "furnished",
        "amenities": ["parking", "security"],
        "society_name": "Koramangala Clubside",
        "square_footage": 990,
        "available_from": "2026-09-05",
        "deposit_amount": 59000,
        "listing_type": "whole flat",
        "food_preference": "veg",
        "smoking_preference": "any",
        "availability_status": "available",
        "latitude": 12.9372,
        "longitude": 77.6261,
    },
    {
        "id": "km-208",
        "source_url": "https://bengaluru.rent/#listing-km-208",
        "location": "Bengaluru",
        "locality": "Koramangala",
        "rent": 34500,
        "bedrooms": 2,
        "furnishing": "semi-furnished",
        "amenities": ["parking", "balcony", "pet-friendly"],
        "society_name": "6th Block Oaks",
        "square_footage": 1120,
        "available_from": "2026-09-10",
        "deposit_amount": 103500,
        "listing_type": "whole flat",
        "food_preference": "any",
        "smoking_preference": "no smoking",
        "availability_status": "available",
        "latitude": 12.9325,
        "longitude": 77.6235,
    },
    {
        "id": "hsr-301",
        "source_url": "https://bengaluru.rent/#listing-hsr-301",
        "location": "Bengaluru",
        "locality": "HSR Layout",
        "rent": 33000,
        "bedrooms": 2,
        "furnishing": "semi-furnished",
        "amenities": ["parking", "balcony"],
        "society_name": "Sector 2 Greens",
        "square_footage": 1100,
        "available_from": "2026-08-22",
        "deposit_amount": 66000,
        "listing_type": "room in a flat",
        "food_preference": "veg",
        "smoking_preference": "no smoking",
        "gender": "male",
        "availability_status": "available",
        "latitude": 12.9116,
        "longitude": 77.6473,
    },
    {
        "id": "ind-401",
        "source_url": "https://bengaluru.rent/#listing-ind-401",
        "location": "Bengaluru",
        "locality": "Indiranagar",
        "rent": 38000,
        "bedrooms": 2,
        "furnishing": "furnished",
        "amenities": ["parking", "balcony", "elevator"],
        "society_name": "100 Feet Road Towers",
        "square_footage": 1150,
        "available_from": "2026-09-01",
        "deposit_amount": 114000,
        "listing_type": "whole flat",
        "food_preference": "non-veg",
        "smoking_preference": "any",
        "availability_status": "available",
        "latitude": 12.9784,
        "longitude": 77.6408,
    },
    {
        "id": "wfd-501",
        "source_url": "https://bengaluru.rent/#listing-wfd-501",
        "location": "Bengaluru",
        "locality": "Whitefield",
        "rent": 29000,
        "bedrooms": 2,
        "furnishing": "semi-furnished",
        "amenities": ["parking", "gym", "pool"],
        "society_name": "ITPL Side Residences",
        "square_footage": 1080,
        "available_from": "2026-09-20",
        "deposit_amount": 58000,
        "listing_type": "whole flat",
        "food_preference": "any",
        "smoking_preference": "smoking allowed",
        "availability_status": "available",
        "latitude": 12.9698,
        "longitude": 77.7499,
    },
    {
        "id": "jyn-601",
        "source_url": "https://bengaluru.rent/#listing-jyn-601",
        "location": "Bengaluru",
        "locality": "Jayanagar",
        "rent": 27000,
        "bedrooms": 2,
        "furnishing": "unfurnished",
        "amenities": ["parking"],
        "society_name": "4th Block Court",
        "square_footage": 950,
        "available_from": "2026-08-21",
        "deposit_amount": 81000,
        "listing_type": "room in a flat",
        "food_preference": "veg",
        "smoking_preference": "no smoking",
        "gender": "any",
        "availability_status": "available",
        "latitude": 12.9308,
        "longitude": 77.5838,
    },
    # Transparency-only / not for rent — must be excluded by normalize
    {
        "id": "km-999",
        "source_url": "https://bengaluru.rent/#listing-km-999",
        "location": "Bengaluru",
        "locality": "Koramangala",
        "rent": 31000,
        "bedrooms": 2,
        "furnishing": "furnished",
        "amenities": ["parking"],
        "society_name": "Transparency Pin",
        "square_footage": 1000,
        "available_from": "2026-12-01",
        "deposit_amount": 62000,
        "listing_type": "room in a flat",
        "food_preference": "any",
        "smoking_preference": "any",
        "gender": "female",
        "availability_status": "Not for rent",
        "latitude": 12.9350,
        "longitude": 77.6240,
        "owner_name": "Hidden",
        "phone": "9000000000",
    },
]
